In [2]:
import numpy as np

In [3]:
np.random.random_integers(5)

<ipython-input-3-fd8ba7eaeca0>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(5)


5

In [4]:
a = np.random.random_integers(5)

<ipython-input-4-bdf2c48bf898>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  a = np.random.random_integers(5)


In [5]:
print(a)

1


In [6]:
np.random.random_integers(5, size=(5, 5))

<ipython-input-6-0de8d0699ee3>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(5, size=(5, 5))


array([[1, 2, 1, 3, 3],
       [4, 1, 3, 2, 3],
       [4, 1, 3, 4, 5],
       [1, 4, 5, 3, 5],
       [2, 4, 3, 5, 5]])

In [1]:
a = b = np.arange(50)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
a = b = np.arange(50)

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [5]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [6]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [7]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])